import FreeCAD
import TechDrawGui
import os

# Get the active document
doc = FreeCAD.ActiveDocument

availableSheets = doc.findObjects("Spreadsheet::Sheet")
dimensionSheet = availableSheets[0]
outputFileName = '{}.pdf'.format(dimensionSheet.project_code)
print(outputFileName)

directory='svg'
if not os.path.exists(directory):
    os.makedirs(directory)

# Check if the document is not empty
if doc is not None:
  # Iterate through all pages in the TechDraw Workbench
  # pages = doc.findObjects("TechDraw::DrawPage")
  pages = doc.getObjectsByLabel("drawings")[0].Group
  pdfFileNames = []
  for page in pages:
    templateTexts = page.Template.EditableTexts
    # 
    svgFileName = '{}/{}_{}.svg'.format(directory,templateTexts["Drawing_number"], templateTexts["FC-SH"])
    print(svgFileName)
    TechDrawGui.exportPageAsSvg(page,svgFileName)
    pdfFileName = '{}/{}_{}.pdf'.format(directory,templateTexts["Drawing_number"], templateTexts["FC-SH"])
    TechDrawGui.exportPageAsPdf(page,pdfFileName)
    pdfFileNames.append(pdfFileName)
  pdftkCommand = f"pdftk {' '.join(pdfFileNames)} output {outputFileName}"
  print(pdftkCommand)
  os.system(pdftkCommand)
  for pdfFileName in pdfFileNames:
    os.remove(pdfFileName)
  os.startfile(outputFileName, 'open')
else:
    print("No active document.")
